import { Member, Tag, Project, Profile } from "./types";

// 목업용 프로필 (auth 없는 개발 환경용)
const PROFILES: Profile[] = [
  { id: "m1", nickname: "김민준", avatar_url: null },
  { id: "m2", nickname: "이서연", avatar_url: null },
  { id: "m3", nickname: "박지훈", avatar_url: null },
  { id: "m4", nickname: "최유진", avatar_url: null },
  { id: "m5", nickname: "정다은", avatar_url: null },
];

export const MEMBERS: Member[] = [
  { id: "m1", name: "김민준", avatar: "김", color: "#6366f1" },
  { id: "m2", name: "이서연", avatar: "이", color: "#f59e0b" },
  { id: "m3", name: "박지훈", avatar: "박", color: "#10b981" },
  { id: "m4", name: "최유진", avatar: "최", color: "#ef4444" },
  { id: "m5", name: "정다은", avatar: "정", color: "#8b5cf6" },
];

export const TAGS: Tag[] = [
  { id: "t1", title: "버그", color: "#ef4444" },
  { id: "t2", title: "기능", color: "#6366f1" },
  { id: "t3", title: "디자인", color: "#f59e0b" },
  { id: "t4", title: "긴급", color: "#dc2626" },
  { id: "t5", title: "QA", color: "#10b981" },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    title: "플랫폼 리뉴얼 2025",
    description: "전체 플랫폼 UI/UX 개선 및 성능 최적화 프로젝트",
    members: [MEMBERS[0], MEMBERS[1], MEMBERS[2], MEMBERS[3]],
    is_starred: true,
    is_ended: false,
    status: "진행중",
    owner_id: null,
    created_at: "2025-01-15",
    columns: [
      { id: "p1-col1", title: "대기", position: 1000, color: "#94a3b8" },
      { id: "p1-col2", title: "진행중", position: 2000, color: "#3b82f6" },
      { id: "p1-col3", title: "완료", position: 3000, color: "#10b981", status: "done" },
    ],
    cards: [
      {
        id: "p1-c1",
        column_id: "p1-col1",
        title: "메인 홈 화면 리디자인",
        description: "홈 화면 전체 레이아웃 개편",
        body: "<p>홈 화면의 전체적인 레이아웃을 개편합니다.</p><ul data-type=\"taskList\"><li data-checked=\"false\"><label><input type=\"checkbox\"><span></span></label><div><p>와이어프레임 검토</p></div></li><li data-checked=\"false\"><label><input type=\"checkbox\"><span></span></label><div><p>디자인 시안 제작</p></div></li></ul>",
        due_date: "2026-04-10",
        assignee: MEMBERS[1],
        stakeholders: [MEMBERS[0], MEMBERS[2]],
        tags: [TAGS[2], TAGS[1]],
        position: 3000,
        created_at: "2026-03-20T10:00:00Z",
        comments: [
          {
            id: "cmt-1",
            author: PROFILES[0],
            content: "와이어프레임 초안 검토 완료했습니다. 전반적으로 방향성이 좋네요.",
            created_at: "2026-03-21T09:30:00Z",
          },
          {
            id: "cmt-2",
            author: PROFILES[2],
            content: "디자인 시안 2안으로 진행하면 좋을 것 같습니다.",
            created_at: "2026-03-22T14:00:00Z",
          },
        ],
        attachments: [
          {
            id: "att-1",
            name: "홈화면_와이어프레임_v2.fig",
            size: 2457600,
            created_at: "2026-03-21T10:00:00Z",
          },
        ],
      },
      {
        id: "p1-c2",
        column_id: "p1-col1",
        title: "검색 기능 UX 개선",
        description: "검색 자동완성 및 필터 UI 개선",
        body: "<p>검색 자동완성 성능 개선 및 필터 UI를 재설계합니다.</p>",
        due_date: "2026-03-20",
        assignee: MEMBERS[0],
        stakeholders: [MEMBERS[1]],
        tags: [TAGS[1]],
        position: 2000,
        created_at: "2026-03-22T09:00:00Z",
        comments: [],
        attachments: [],
      },
      {
        id: "p1-c3",
        column_id: "p1-col2",
        title: "로그인 플로우 버그 수정",
        description: "소셜 로그인 실패 케이스 처리",
        body: "<p>소셜 로그인 시 특정 케이스에서 무한 로딩이 발생하는 버그를 수정합니다.</p>",
        due_date: "2026-03-15",
        assignee: MEMBERS[2],
        stakeholders: [MEMBERS[3]],
        tags: [TAGS[0], TAGS[3]],
        position: 3000,
        created_at: "2026-03-18T14:00:00Z",
        comments: [
          {
            id: "cmt-3",
            author: PROFILES[3],
            content: "재현 방법 확인했습니다. 카카오 로그인에서만 발생하는 문제네요.",
            created_at: "2026-03-19T10:00:00Z",
          },
        ],
        attachments: [
          {
            id: "att-2",
            name: "버그_재현_영상.mp4",
            size: 15728640,
            created_at: "2026-03-19T09:00:00Z",
          },
          {
            id: "att-3",
            name: "에러_로그.txt",
            size: 4096,
            created_at: "2026-03-19T09:05:00Z",
          },
        ],
      },
      {
        id: "p1-c4",
        column_id: "p1-col2",
        title: "API 응답 속도 최적화",
        description: "주요 API 엔드포인트 캐싱 적용",
        body: "<p>Redis 캐싱을 적용하여 API 응답 속도를 개선합니다.</p>",
        due_date: "2026-04-05",
        assignee: MEMBERS[0],
        stakeholders: [],
        tags: [TAGS[1]],
        position: 2000,
        created_at: "2026-03-21T11:00:00Z",
        comments: [],
        attachments: [],
      },
      {
        id: "p1-c5",
        column_id: "p1-col3",
        title: "다크모드 지원",
        description: "전체 페이지 다크모드 구현 완료",
        body: "<p>CSS 변수 기반으로 다크모드를 구현하였습니다.</p>",
        due_date: "2026-03-01",
        assignee: MEMBERS[1],
        stakeholders: [MEMBERS[4]],
        tags: [TAGS[2], TAGS[4]],
        position: 3000,
        created_at: "2026-02-20T09:00:00Z",
        comments: [],
        attachments: [],
      },
    ],
  },
  {
    id: "p2",
    title: "모바일 앱 v2.0",
    description: "iOS/Android 앱 메이저 업데이트",
    members: [MEMBERS[0], MEMBERS[2], MEMBERS[4]],
    is_starred: true,
    is_ended: false,
    status: "진행중",
    owner_id: null,
    created_at: "2025-02-01",
    columns: [
      { id: "p2-col1", title: "대기", position: 1000, color: "#94a3b8" },
      { id: "p2-col2", title: "진행중", position: 2000, color: "#3b82f6" },
      { id: "p2-col3", title: "완료", position: 3000, color: "#10b981", status: "done" },
    ],
    cards: [
      {
        id: "p2-c1",
        column_id: "p2-col1",
        title: "푸시 알림 설정 화면",
        description: "알림 종류별 on/off 설정",
        body: "<p>사용자별 알림 설정을 세분화합니다.</p>",
        due_date: "2026-04-20",
        assignee: MEMBERS[4],
        stakeholders: [MEMBERS[0]],
        tags: [TAGS[1]],
        position: 2000,
        created_at: "2026-03-23T10:00:00Z",
        comments: [],
        attachments: [],
      },
      {
        id: "p2-c2",
        column_id: "p2-col2",
        title: "온보딩 플로우 개선",
        description: "신규 유저 온보딩 3단계로 축소",
        body: "<p>복잡한 온보딩을 3단계로 간소화합니다.</p><ul data-type=\"taskList\"><li data-checked=\"true\"><label><input type=\"checkbox\" checked><span></span></label><div><p>기획 완료</p></div></li><li data-checked=\"false\"><label><input type=\"checkbox\"><span></span></label><div><p>개발 진행중</p></div></li></ul>",
        due_date: "2026-03-25",
        assignee: MEMBERS[2],
        stakeholders: [MEMBERS[0], MEMBERS[4]],
        tags: [TAGS[2], TAGS[1]],
        position: 3000,
        created_at: "2026-03-15T09:00:00Z",
        comments: [
          {
            id: "cmt-4",
            author: PROFILES[0],
            content: "3단계 구성안 공유드립니다. 확인 부탁드려요.",
            created_at: "2026-03-16T10:00:00Z",
          },
        ],
        attachments: [
          {
            id: "att-4",
            name: "온보딩_플로우_기획서.pdf",
            size: 1048576,
            created_at: "2026-03-16T09:00:00Z",
          },
        ],
      },
      {
        id: "p2-c3",
        column_id: "p2-col3",
        title: "앱 아이콘 업데이트",
        description: "새로운 브랜드 가이드 반영",
        body: "<p>새로운 브랜드 아이덴티티에 맞게 앱 아이콘을 교체했습니다.</p>",
        due_date: "2026-02-28",
        assignee: MEMBERS[0],
        stakeholders: [],
        tags: [TAGS[2]],
        position: 3000,
        created_at: "2026-02-10T09:00:00Z",
        comments: [],
        attachments: [],
      },
    ],
  },
  {
    id: "p3",
    title: "데이터 분석 대시보드",
    description: "내부 운영팀용 데이터 시각화 툴",
    members: [MEMBERS[1], MEMBERS[3]],
    is_starred: false,
    is_ended: false,
    status: "대기",
    owner_id: null,
    created_at: "2025-03-10",
    columns: [
      { id: "p3-col1", title: "대기", position: 1000, color: "#94a3b8" },
      { id: "p3-col2", title: "진행중", position: 2000, color: "#3b82f6" },
      { id: "p3-col3", title: "완료", position: 3000, color: "#10b981", status: "done" },
    ],
    cards: [
      {
        id: "p3-c1",
        column_id: "p3-col1",
        title: "일별 활성 사용자 차트",
        description: "DAU 추이 라인 차트 구현",
        body: "<p>Recharts 라이브러리를 사용하여 DAU 차트를 구현합니다.</p>",
        due_date: "2026-04-15",
        assignee: MEMBERS[3],
        stakeholders: [MEMBERS[1]],
        tags: [TAGS[1]],
        position: 2000,
        created_at: "2026-03-24T10:00:00Z",
        comments: [],
        attachments: [],
      },
      {
        id: "p3-c2",
        column_id: "p3-col2",
        title: "매출 리포트 엑셀 다운로드",
        description: "기간별 매출 데이터 엑셀 추출",
        body: "<p>xlsx 라이브러리로 엑셀 다운로드 기능을 구현합니다.</p>",
        due_date: "2026-03-10",
        assignee: MEMBERS[1],
        stakeholders: [],
        tags: [TAGS[1], TAGS[3]],
        position: 3000,
        created_at: "2026-03-05T09:00:00Z",
        comments: [],
        attachments: [],
      },
    ],
  },
  {
    id: "p4",
    title: "CS 자동화 시스템",
    description: "고객 문의 자동 분류 및 응답 시스템",
    members: [MEMBERS[0], MEMBERS[1], MEMBERS[2], MEMBERS[3], MEMBERS[4]],
    is_starred: false,
    is_ended: false,
    status: "진행중",
    owner_id: null,
    created_at: "2025-04-01",
    columns: [
      { id: "p4-col1", title: "대기", position: 1000, color: "#94a3b8" },
      { id: "p4-col2", title: "진행중", position: 2000, color: "#3b82f6" },
      { id: "p4-col3", title: "완료", position: 3000, color: "#10b981", status: "done" },
    ],
    cards: [
      {
        id: "p4-c1",
        column_id: "p4-col1",
        title: "문의 카테고리 분류 모델",
        description: "NLP 기반 자동 분류 모델 학습",
        body: "<p>scikit-learn을 사용하여 문의 카테고리 분류 모델을 학습합니다.</p>",
        due_date: "2026-05-01",
        assignee: MEMBERS[2],
        stakeholders: [MEMBERS[0]],
        tags: [TAGS[1]],
        position: 2000,
        created_at: "2026-03-25T10:00:00Z",
        comments: [],
        attachments: [],
      },
    ],
  },
  {
    id: "p5",
    title: "레거시 어드민 마이그레이션",
    description: "구 어드민 시스템 Next.js 전환 (완료)",
    members: [MEMBERS[0], MEMBERS[3]],
    is_starred: false,
    is_ended: true,
    status: "종료",
    owner_id: null,
    created_at: "2024-06-01",
    columns: [
      { id: "p5-col1", title: "대기", position: 1000, color: "#94a3b8" },
      { id: "p5-col2", title: "진행중", position: 2000, color: "#3b82f6" },
      { id: "p5-col3", title: "완료", position: 3000, color: "#10b981", status: "done" },
    ],
    cards: [
      {
        id: "p5-c1",
        column_id: "p5-col3",
        title: "사용자 관리 페이지 마이그레이션",
        description: "완료",
        body: "<p>성공적으로 마이그레이션 완료.</p>",
        due_date: "2024-12-31",
        assignee: MEMBERS[0],
        stakeholders: [],
        tags: [TAGS[4]],
        position: 3000,
        created_at: "2024-11-01T09:00:00Z",
        comments: [],
        attachments: [],
      },
    ],
  },
];
